server:
  port: 8999
  maxHttpHeaderSize: 4194304
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 2097162
spring:
  aop:
    auto: true
    proxy-target-class: true
  application:
    name: uniubi-microservice-medusa-es-demo
  http:
    encoding:
      force: true
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: 3MB
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  #Redis配置
#  redis:
#    #使用的redis database序号
#    database: 7
#    host: 192.168.1.172
#    port: 6379
#    password: Uni@ubi123
#    jedis:
#      pool:
#        #最大连接数
#        max-active: 300
#        #最大阻塞等待时间(负数表示没限制)
#        max-wait: -1
#        #最大空闲
#        max-idle: 100
#        #最小空闲
#        min-idle: 0
#    #连接超时时间
#    timeout: 3000


elasticsearch:
  ip: localhost
  port: 9300
  pool: 5
  cluster:
    name: medusa-es
  index: medusa-es
